# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11yk0clvu1LX-gLLjlc72D6zP-5a4yFHd
"""

import csv 
def isempty3(): 
  if len(stack)==0: 
    return "underflow" 
sum=0 
sale1=0 
units=0 
count=0 
sale2=0 
L=[] 
L2=[] 
co_name=() 
a_name=() 
car_name=() 
stack=[] 
stack1=[] 
stack2=[] 
print(" WELCOME TO ABC CARS") 
ch2=1 
while ch2!=9: 
  print(" ENTER 1 TO CHECK AND UPDATE THE STOCK\n ENTER 2 TO CHECK AND UPDATE THE SALE\n ENTER 3 TO SEE AND UPDATE PRE-BOOKED ORDERS\n ENTER 4 TO SEE THE EXPECTED ANNUAL SALE\n ENTER 5 TO SEE AND ADD CUSTOMER DETAILS\n ENTER 6 TO REVIEW OR PROCESS A CUSTOMER'S LOAN\n ENTER 7 TO PLACE AN ORDER FOR STORE\n ENTER 8 TO SEARCH INFORMATION ABOUT A CAR\n ENTER 9 TO EXIT ") 
  ch2=int(input("ENTER WHAT DO YOU WISH TO DO?")) 
  if ch2==1: 
    def isempty(): 
      if len(stack)==0: 
        return "underflow" 
    def push(): 
      car_name=input("ENTER CAR NAME") 
      price=int(input("ENTER CAR PRICE")) 
      units=int(input("ENTER NO. OF UNITS AVAILABLE")) 
      val=(car_name,price,units) 
      stack.append(val) 
    def pop(): 
      if isempty()=="underflow": 
        print("PLEASE ENTER DATA AND THEN TRY AGAIN") 
      else: 
        stack.pop() 
    def display(): 
      k=isempty() 
      if k=="underflow": 
        print("PLEASE ENTER DATA AND THEN TRY AGAIN") 
      else: 
        for i in range(len(stack)-1,-1,-1): 
          print("NAME OF CAR IS",stack[i][0]) 
          print("PRICE IS",stack[i][1]) 
          print("NO. OF UNITS IS",stack[i][2]) 
    stack=[]
    ch1=1 
    while ch1!=4: 
      print("1. TO ADD A CAR\n2. TO REMOVE DETAILS OF A CAR\n3. DISPLAY THE CARS AVAILABLE IN STOCK\n4. EXIT") 
      ch1=int(input("ENTER YOUR CHOICE")) 
      if ch1==1: 
        push() 
      elif ch1==2: 
        pop() 
      elif ch1==3: 
        display() 
      elif ch1==4: 
        print("THANKS") 
      else: 
        print("ENTER BETWEEN 1 TO 4") 
    with open("stocks.csv","w+")as file: 
      ch='yes' 
      w=csv.writer(file) 
      for i in range(len(stack)-1,-1,-1): 
        w.writerow(stack[i]) 
  elif ch2==2: 
    with open("sales.csv","w+",newline='')as f: 
      ch='' 
      w=csv.writer(f) 
      while ch!="no": 
        c_name=input("ENTER CAR NAME") 
        p=int(input("ENTER PRICE")) 
        u=int(input("ENTER NO. OF UNITS SOLD")) 
        l=(c_name,p,u) 
        w.writerow(l) 
        ch=input("MORE?") 
        if p>0 and u>0: 
          sum=sum+p*u 
          units=units+u 
        sale1=sum 
      print("THE TOTAL SALE IS",sum)
      print("THE TOTAL UNITS SOLD ARE",units) 
  elif ch2==3: 
    with open("prebookings.csv","w+",newline="")as f1: 
      ch='yes' 
      w1=csv.writer(f1) 
      while ch!='no': 
        v_name=input("ENTER NAME OF THE CAR PRE-BOOKED") 
        cost=int(input("ENTER PRICE")) 
        unit=int(input("ENTER NO. OF UNITS BOOKED")) 
        m=(v_name,cost,unit) 
        w1.writerow(m) 
        ch=input("MORE?") 
        if cost>0: 
          sale2=sale2+cost*unit 
  elif ch2==4: 
    sale3=sale1+sale2 
    print("THE ESTIMATED ANNUAL SALE TILL NOW IS Rs.",sale3,"\n") 
  elif ch2==5: 
    def isempty1(): 
      if len(stack1)==0: 
        return "underflow" 
    def push1(): 
      customer_name=input("ENTER CUSTOMER NAME") 
      m_no=int(input("ENTER MOBILE NUMBER OF A CUSTOMER")) 
      address=input("ENTER ADDRESS OF THE CUSTOMER") 
      val1=(customer_name,m_no,address) 
      stack1.append(val1) 
    def pop1(): 
      if isempty1()=="underflow": 
        print("PLEASE ENTER DATA AND THEN TRY AGAIN") 
      else:
        stack1.pop() 
    def display1(): 
      k=isempty1() 
      if k=="underflow": 
        print("PLEASE ENTER DATA AND THEN TRY AGAIN") 
      else: 
        for i in range(len(stack1)-1,-1,-1): 
          print("NAME OF THE CUSTOMER",stack1[i][0]) 
          print("MOBILE NO. OF THE CUSTOMER",stack1[i][1]) 
          print("ADDRESS OF THE CUSTOMER IS",stack1[i][2]) 
    stack1=[] 
    ch3=1 
    print(" 1. ENTER DETAILS OF A CUSTOMER\n 2. REMOVE DETAILS OF A CUSTOMER\n 3. DISPLAY DETAILS OF CUSTOMERS\n 4. EXIT") 
      while ch3!=4: 
        ch3=int(input("ENTER YOUR CHOICE")) 
        if ch3==1: 
          push1() 
        elif ch3==2: 
          pop1() 
        elif ch3==3: 
          display1() 
        elif ch3==4: 
          print("THANKS") 
        else: 
          print("ENTER BETWEEN 1-4") 
      with open("customer.csv","w+",newline='')as f2: 
        ch='yes' 
        w2=csv.writer(f2) 
        for i in range(len(stack1)-1,-1,-1): 
          w2.writerow(stack1[i])
    elif ch2==6: 
      def isempty2():
        if len(stack2)==0: 
          return "underflow" 
      def push2(): 
        cust_name=input("ENTER NAME CUSTOMER APPLYING FOR LOAN") 
        loan_amt=int(input("ENTER LOAN AMOUNT")) 
        t=int(input("ENTER TIME PERIOD FOR LOAN(IN MONTHS)")) 
        emi=int(input("ENTER EMI TO BE CHARGED(IN RUPEES PER MONTH)")) 
        amt2=loan_amt+emi*t 
        val2=(cust_name,loan_amt,t,emi,amt2) 
        stack2.append(val2) 
      def pop2(): 
        if isempty1()=="underflow": 
          print("PLEASE ENTER DATA AND THEN TRY AGAIN") 
        else: 
          stack2.pop() 
      def display2(): 
        k=isempty2() 
        if k=="underflow": 
          print("PLEASE ENTER DATA AND THEN TRY AGAIN") 
        else: 
          for i in range(len(stack2)-1,-1,-1): 
            print("\n") 
            print("NAME OF THE CUSTOMER APPLYING FOR 
            LOAN IS",stack2[i][0]) 
            print("AMOUNT TAKEN AS LOAN IS",stack2[i][1]) 
            print("TIME PERIOD FOR LOAN REPAYMENT 
            IS",stack2[i][2]) 
            print("EMI TO BE CHARGED IS",stack2[i][3]) 
            print("AMOUNT TO BE REPAID IS",stack2[i][4]) 
      stack2=[] 
      ch5=1
      print(" 1. PROCESS FOR A NEW LOAN\n 2. STOP/CANCEL A LOAN\n 3. DISPLAY DETAILS OF LOANS BEING PROCESSED\n 4. EXIT") 
      while ch5!=4: 
        ch5=int(input("ENTER YOUR CHOICE")) 
        if ch5==1: 
          push2() 
        elif ch5==2: 
          pop2() 
        elif ch5==3: 
          display2() 
        elif ch5==4: 
          print("THANKS") 
        else: 
          print("ENTER BETWEEN 1-4") 
      with open("loan.csv","w+",newline='')as f4: 
        w3=csv.writer(f4) 
        for i in range(len(stack2)-1,-1,-1): 
          w3.writerow(stack2[i]) 
    elif ch2==7: 
      ch0=1 
      while ch0!=3: 
        print(" ENTER 1 TO PLACE ORDER FOR CARS\n ENTER 2 TO PLACE AN ORDER FOR ACCESSORIES\n ENTER 3 TO EXIT") 
        ch0=int(input("ENTER YOUR CHOICE")) 
        if ch0==1: 
          co_name=input("ENTER NAME OF CAR TO BE ORDERED") 
          pri=int(input("ENTER ITS PRICE")) 
          uni=int(input("ENTER NUMBER OF UNITS TO BE ORDERED")) 
          val9=(co_name,pri,uni) 
          L.append(val9) 
        elif ch0==2: 
          a_name=input("ENTER NAME OF THE ACCESORY 
          YOU WANT TO ORDER") 
          cost2=int(input("ENTER THE COST"))
          quan=int(input("ENTER NO. OF PIECES YOU WANT TO ORDER")) 
          val0=(a_name,cost2,quan) 
          L2.append(val0) 
        elif ch0==3: 
          if co_name!=(): 
            print(L) 
          if a_name!=(): 
            print(L2) 
          print("THESE ARE YOUR ORDERS....THANKS","\n") 
          print("THANK YOU FOR YOUR ORDER") 
        else: 
          print("ENTER BETWEEN 1-3") 
    elif ch2==8: 
      ch5=1 
      while ch5!=3: 
        print(" ENTER 1 TO KNOW THE PRICE OF A CAR\n ENTER 2 TO KNOW THE NUMBER OF UNITS AVAILABLE\n ENTER 3 TO EXIT") 
        ch5=int(input("ENTER WHAT DO YOU WISH TO DO?")) 
        if ch5==1: 
          if stack==isempty3(): 
            print("STOCK EMPTY..PLEASE PLACE AN ORDER USING OPTION 7 OF OUR FIRST MENU") 
          else: 
            found=-1 
            car_name=input("ENTER NAME OF THE CAR YOU WANT TO SEARCH FOR") 
            for i in range(len(stack)-1,-1,-1): 
              if stack[i][0]==car_name: 
                print("THE PRICE OF THE CAR YOU SEARCHED FOR IS Rs.",stack[i][1]) 
                found=1 
                break 
            if found==-1: 
              print("CAR NOT IN STOCK..CHECK THE STOCK AND TRY AGAIN") 
        elif ch5==2:
          car_name=input("ENTER NAME OF THE CAR YOU WANT TO SEARCH FOR") 
          if stack==isempty3(): 
            print("STOCK EMPTY..PLEASE PLACE AN ORDER USING OPTION 7 OF OUR FIRST MENU") 
          else: 
          found=-2 
          car_name=input("ENTER NAME OF THE CAR YOU WANT TO SEARCH FOR") 
          for i in range(len(stack)-1,-1,-1): 
            if stack[i][0]==car_name: 
              print("THE NUMBER OF UNITS OF THE CAR YOU SEARCHED FOR IS",stack[i][2]) 
              found=2 
          if found==-2: 
            print("CAR NOT IN STOCK..CHECK THE STOCK AND TRY AGAIN") 
          elif ch5==3: 
            print(" THANK YOU") 
          else: 
            print(" ENTER BETWEEN 1 TO 3") 
    elif ch2==9: 
      print(" THANKS..SEE YOU AGAIN") 
    else: 
      print("ENTER BETWEEN 1-9")